# Generated by Django 3.2.16 on 2024-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
