# Generated by Django 3.2.16 on 2024-11-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
